version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/infra/network"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/infra/dns"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/infra/cloudflare"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/infra/storage"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/compute/vm"
    schedule:
      interval: "weekly"
