name: Deploy Compute

on:
  workflow_dispatch:
    inputs:
      apply:
        description: 'Applying the changes'
        type: boolean
        default: false
  push:
    paths:
      - 'compute/vm/**'
      - '.github/workflows/deploy-compute.yml'

defaults:
  run:
    working-directory: compute/vm

jobs:
  terraform:
    name: Terraform Compute
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TF_VAR_dns_zone_name: ${{ secrets.DNS_ZONE_NAME }}
      TF_VAR_dns_rg_name: ${{ secrets.RESOURCE_GROUP_NAME }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.event_name == 'workflow_dispatch' && inputs.apply == true
        run: terraform apply -auto-approve tfplan
