name: Deploy Cloudflare

on:
  workflow_dispatch:
    inputs:
      apply:
        description: 'Applying the changes'
        type: boolean
        default: false
  workflow_call:
    inputs:
      apply:
        required: false
        type: boolean
        default: false
  push:
    paths:
      - 'infra/cloudflare/**'
      - '.github/workflows/deploy-cloudflare.yml'

jobs:
  terraform:
    name: Terraform Cloudflare
    uses: ./.github/workflows/_terraform.yml
    secrets: inherit
    with:
      working_directory: infra/cloudflare
      apply: ${{ inputs.apply == true }}
