name: Deploy DNS

on:
  workflow_dispatch:
    inputs:
      apply:
        description: 'Applying the changes'
        type: boolean
        default: false
  workflow_call:
    inputs:
      apply:
        required: false
        type: boolean
        default: false
  push:
    paths:
      - 'infra/dns/**'
      - '.github/workflows/deploy-dns.yml'

jobs:
  terraform:
    name: Terraform DNS
    uses: ./.github/workflows/_terraform.yml
    secrets: inherit
    with:
      working_directory: infra/dns
      apply: ${{ inputs.apply == true }}
