name: Deploy Network

on:
  workflow_dispatch:
    inputs:
      ssh_source_ip:
        description: 'The IP address to whitelist for SSH access (e.g., 1.2.3.4/32). Leave empty to use the runner IP (not recommended as it changes).'
        required: false
        type: string
      apply:
        description: 'Applying the changes'
        type: boolean
        default: false
  workflow_call:
    inputs:
      ssh_source_ip:
        required: false
        type: string
      apply:
        required: false
        type: boolean
        default: false
  push:
    paths:
      - 'infra/network/**'
      - '.github/workflows/deploy-network.yml'

jobs:
  terraform:
    name: Terraform Network
    uses: ./.github/workflows/_terraform.yml
    secrets: inherit
    with:
      working_directory: infra/network
      ssh_source_ip: ${{ inputs.ssh_source_ip }}
      apply: ${{ inputs.apply == true }}
